// This file was auto-generated by ML.NET Model Builder. 

namespace MyFirstMLProject.Models
{
    using Microsoft.ML.Data;

    public class InputModel
    {
        [ColumnName("Date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("Days"), LoadColumn(1)]
        public float Days { get; set; }


        [ColumnName("Task"), LoadColumn(2)]
        public string Task { get; set; }


        [ColumnName("Department"), LoadColumn(3)]
        public string Department { get; set; }


        [ColumnName("Section"), LoadColumn(4)]
        public string Section { get; set; }


        [ColumnName("Minutes"), LoadColumn(5)]
        public float Minutes { get; set; }


        [ColumnName("CountTasks"), LoadColumn(6)]
        public float CountTasks { get; set; }


        [ColumnName("FTEs"), LoadColumn(7)]
        public float FTEs { get; set; }


    }
}